//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.30 at 09:30:35 AM EDT 
//


package jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="technique_common">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="angular_velocity" type="{http://www.collada.org/2005/11/COLLADASchema}float3" minOccurs="0"/>
 *                   &lt;element name="velocity" type="{http://www.collada.org/2005/11/COLLADASchema}float3" minOccurs="0"/>
 *                   &lt;element name="dynamic" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
 *                           &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="mass" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
 *                   &lt;element name="mass_frame" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded">
 *                             &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}translate"/>
 *                             &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}rotate"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="inertia" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat3" minOccurs="0"/>
 *                   &lt;choice minOccurs="0">
 *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_physics_material"/>
 *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}physics_material"/>
 *                   &lt;/choice>
 *                   &lt;element name="shape" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hollow" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
 *                                     &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="mass" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
 *                             &lt;element name="density" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
 *                             &lt;choice minOccurs="0">
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_physics_material"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}physics_material"/>
 *                             &lt;/choice>
 *                             &lt;choice>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_geometry"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}plane"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}box"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}sphere"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}cylinder"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}tapered_cylinder"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}capsule"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}tapered_capsule"/>
 *                             &lt;/choice>
 *                             &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}translate"/>
 *                               &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}rotate"/>
 *                             &lt;/choice>
 *                             &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}technique" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="body" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "techniqueCommon",
    "techniques",
    "extras"
})
@XmlRootElement(name = "instance_rigid_body")
public class InstanceRigidBody {

    @XmlElement(name = "technique_common", required = true)
    protected InstanceRigidBody.TechniqueCommon techniqueCommon;
    @XmlElement(name = "technique")
    protected List<Technique> techniques;
    @XmlElement(name = "extra")
    protected List<Extra> extras;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String body;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sid;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String target;

    /**
     * Gets the value of the techniqueCommon property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceRigidBody.TechniqueCommon }
     *     
     */
    public InstanceRigidBody.TechniqueCommon getTechniqueCommon() {
        return techniqueCommon;
    }

    /**
     * Sets the value of the techniqueCommon property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceRigidBody.TechniqueCommon }
     *     
     */
    public void setTechniqueCommon(InstanceRigidBody.TechniqueCommon value) {
        this.techniqueCommon = value;
    }

    /**
     * 
     * 						This element may contain any number of non-common profile techniques.
     * 						Gets the value of the techniques property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the techniques property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechniques().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Technique }
     * 
     * 
     */
    public List<Technique> getTechniques() {
        if (techniques == null) {
            techniques = new ArrayList<Technique>();
        }
        return this.techniques;
    }

    /**
     * 
     * 						The extra element may appear any number of times.
     * 						Gets the value of the extras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extra }
     * 
     * 
     */
    public List<Extra> getExtras() {
        if (extras == null) {
            extras = new ArrayList<Extra>();
        }
        return this.extras;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBody(String value) {
        this.body = value;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="angular_velocity" type="{http://www.collada.org/2005/11/COLLADASchema}float3" minOccurs="0"/>
     *         &lt;element name="velocity" type="{http://www.collada.org/2005/11/COLLADASchema}float3" minOccurs="0"/>
     *         &lt;element name="dynamic" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
     *                 &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mass" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
     *         &lt;element name="mass_frame" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded">
     *                   &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}translate"/>
     *                   &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}rotate"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="inertia" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat3" minOccurs="0"/>
     *         &lt;choice minOccurs="0">
     *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_physics_material"/>
     *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}physics_material"/>
     *         &lt;/choice>
     *         &lt;element name="shape" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hollow" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
     *                           &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="mass" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
     *                   &lt;element name="density" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
     *                   &lt;choice minOccurs="0">
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_physics_material"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}physics_material"/>
     *                   &lt;/choice>
     *                   &lt;choice>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_geometry"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}plane"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}box"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}sphere"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}cylinder"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}tapered_cylinder"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}capsule"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}tapered_capsule"/>
     *                   &lt;/choice>
     *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}translate"/>
     *                     &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}rotate"/>
     *                   &lt;/choice>
     *                   &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "angularVelocity",
        "velocity",
        "dynamic",
        "mass",
        "massFrame",
        "inertia",
        "physicsMaterial",
        "instancePhysicsMaterial",
        "shapes"
    })
    public static class TechniqueCommon {

        @XmlList
        @XmlElement(name = "angular_velocity", type = Double.class, defaultValue = "0.0 0.0 0.0")
        protected List<Double> angularVelocity;
        @XmlList
        @XmlElement(type = Double.class, defaultValue = "0.0 0.0 0.0")
        protected List<Double> velocity;
        protected InstanceRigidBody.TechniqueCommon.Dynamic dynamic;
        protected TargetableFloat mass;
        @XmlElement(name = "mass_frame")
        protected InstanceRigidBody.TechniqueCommon.MassFrame massFrame;
        protected TargetableFloat3 inertia;
        @XmlElement(name = "physics_material")
        protected PhysicsMaterial physicsMaterial;
        @XmlElement(name = "instance_physics_material")
        protected InstanceWithExtra instancePhysicsMaterial;
        @XmlElement(name = "shape")
        protected List<InstanceRigidBody.TechniqueCommon.Shape> shapes;

        /**
         * Gets the value of the angularVelocity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the angularVelocity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAngularVelocity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getAngularVelocity() {
            if (angularVelocity == null) {
                angularVelocity = new ArrayList<Double>();
            }
            return this.angularVelocity;
        }

        /**
         * Gets the value of the velocity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the velocity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVelocity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getVelocity() {
            if (velocity == null) {
                velocity = new ArrayList<Double>();
            }
            return this.velocity;
        }

        /**
         * Gets the value of the dynamic property.
         * 
         * @return
         *     possible object is
         *     {@link InstanceRigidBody.TechniqueCommon.Dynamic }
         *     
         */
        public InstanceRigidBody.TechniqueCommon.Dynamic getDynamic() {
            return dynamic;
        }

        /**
         * Sets the value of the dynamic property.
         * 
         * @param value
         *     allowed object is
         *     {@link InstanceRigidBody.TechniqueCommon.Dynamic }
         *     
         */
        public void setDynamic(InstanceRigidBody.TechniqueCommon.Dynamic value) {
            this.dynamic = value;
        }

        /**
         * Gets the value of the mass property.
         * 
         * @return
         *     possible object is
         *     {@link TargetableFloat }
         *     
         */
        public TargetableFloat getMass() {
            return mass;
        }

        /**
         * Sets the value of the mass property.
         * 
         * @param value
         *     allowed object is
         *     {@link TargetableFloat }
         *     
         */
        public void setMass(TargetableFloat value) {
            this.mass = value;
        }

        /**
         * Gets the value of the massFrame property.
         * 
         * @return
         *     possible object is
         *     {@link InstanceRigidBody.TechniqueCommon.MassFrame }
         *     
         */
        public InstanceRigidBody.TechniqueCommon.MassFrame getMassFrame() {
            return massFrame;
        }

        /**
         * Sets the value of the massFrame property.
         * 
         * @param value
         *     allowed object is
         *     {@link InstanceRigidBody.TechniqueCommon.MassFrame }
         *     
         */
        public void setMassFrame(InstanceRigidBody.TechniqueCommon.MassFrame value) {
            this.massFrame = value;
        }

        /**
         * Gets the value of the inertia property.
         * 
         * @return
         *     possible object is
         *     {@link TargetableFloat3 }
         *     
         */
        public TargetableFloat3 getInertia() {
            return inertia;
        }

        /**
         * Sets the value of the inertia property.
         * 
         * @param value
         *     allowed object is
         *     {@link TargetableFloat3 }
         *     
         */
        public void setInertia(TargetableFloat3 value) {
            this.inertia = value;
        }

        /**
         * Gets the value of the physicsMaterial property.
         * 
         * @return
         *     possible object is
         *     {@link PhysicsMaterial }
         *     
         */
        public PhysicsMaterial getPhysicsMaterial() {
            return physicsMaterial;
        }

        /**
         * Sets the value of the physicsMaterial property.
         * 
         * @param value
         *     allowed object is
         *     {@link PhysicsMaterial }
         *     
         */
        public void setPhysicsMaterial(PhysicsMaterial value) {
            this.physicsMaterial = value;
        }

        /**
         * Gets the value of the instancePhysicsMaterial property.
         * 
         * @return
         *     possible object is
         *     {@link InstanceWithExtra }
         *     
         */
        public InstanceWithExtra getInstancePhysicsMaterial() {
            return instancePhysicsMaterial;
        }

        /**
         * Sets the value of the instancePhysicsMaterial property.
         * 
         * @param value
         *     allowed object is
         *     {@link InstanceWithExtra }
         *     
         */
        public void setInstancePhysicsMaterial(InstanceWithExtra value) {
            this.instancePhysicsMaterial = value;
        }

        /**
         * Gets the value of the shapes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shapes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShapes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InstanceRigidBody.TechniqueCommon.Shape }
         * 
         * 
         */
        public List<InstanceRigidBody.TechniqueCommon.Shape> getShapes() {
            if (shapes == null) {
                shapes = new ArrayList<InstanceRigidBody.TechniqueCommon.Shape>();
            }
            return this.shapes;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
         *       &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Dynamic {

            @XmlValue
            protected boolean value;
            @XmlAttribute
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NCName")
            protected String sid;

            /**
             * Gets the value of the value property.
             * 
             */
            public boolean isValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(boolean value) {
                this.value = value;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded">
         *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}translate"/>
         *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}rotate"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "translatesAndRotates"
        })
        public static class MassFrame {

            @XmlElements({
                @XmlElement(name = "rotate", type = Rotate.class),
                @XmlElement(name = "translate", type = TargetableFloat3 .class)
            })
            protected List<Object> translatesAndRotates;

            /**
             * Gets the value of the translatesAndRotates property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the translatesAndRotates property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTranslatesAndRotates().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Rotate }
             * {@link TargetableFloat3 }
             * 
             * 
             */
            public List<Object> getTranslatesAndRotates() {
                if (translatesAndRotates == null) {
                    translatesAndRotates = new ArrayList<Object>();
                }
                return this.translatesAndRotates;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hollow" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
         *                 &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="mass" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
         *         &lt;element name="density" type="{http://www.collada.org/2005/11/COLLADASchema}TargetableFloat" minOccurs="0"/>
         *         &lt;choice minOccurs="0">
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_physics_material"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}physics_material"/>
         *         &lt;/choice>
         *         &lt;choice>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}instance_geometry"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}plane"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}box"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}sphere"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}cylinder"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}tapered_cylinder"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}capsule"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}tapered_capsule"/>
         *         &lt;/choice>
         *         &lt;choice maxOccurs="unbounded" minOccurs="0">
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}translate"/>
         *           &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}rotate"/>
         *         &lt;/choice>
         *         &lt;element ref="{http://www.collada.org/2005/11/COLLADASchema}extra" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hollow",
            "mass",
            "density",
            "physicsMaterial",
            "instancePhysicsMaterial",
            "taperedCapsule",
            "capsule",
            "taperedCylinder",
            "cylinder",
            "sphere",
            "box",
            "plane",
            "instanceGeometry",
            "translatesAndRotates",
            "extras"
        })
        public static class Shape {

            protected InstanceRigidBody.TechniqueCommon.Shape.Hollow hollow;
            protected TargetableFloat mass;
            protected TargetableFloat density;
            @XmlElement(name = "physics_material")
            protected PhysicsMaterial physicsMaterial;
            @XmlElement(name = "instance_physics_material")
            protected InstanceWithExtra instancePhysicsMaterial;
            @XmlElement(name = "tapered_capsule")
            protected TaperedCapsule taperedCapsule;
            protected Capsule capsule;
            @XmlElement(name = "tapered_cylinder")
            protected TaperedCylinder taperedCylinder;
            protected Cylinder cylinder;
            protected Sphere sphere;
            protected Box box;
            protected Plane plane;
            @XmlElement(name = "instance_geometry")
            protected InstanceGeometry instanceGeometry;
            @XmlElements({
                @XmlElement(name = "rotate", type = Rotate.class),
                @XmlElement(name = "translate", type = TargetableFloat3 .class)
            })
            protected List<Object> translatesAndRotates;
            @XmlElement(name = "extra")
            protected List<Extra> extras;

            /**
             * Gets the value of the hollow property.
             * 
             * @return
             *     possible object is
             *     {@link InstanceRigidBody.TechniqueCommon.Shape.Hollow }
             *     
             */
            public InstanceRigidBody.TechniqueCommon.Shape.Hollow getHollow() {
                return hollow;
            }

            /**
             * Sets the value of the hollow property.
             * 
             * @param value
             *     allowed object is
             *     {@link InstanceRigidBody.TechniqueCommon.Shape.Hollow }
             *     
             */
            public void setHollow(InstanceRigidBody.TechniqueCommon.Shape.Hollow value) {
                this.hollow = value;
            }

            /**
             * Gets the value of the mass property.
             * 
             * @return
             *     possible object is
             *     {@link TargetableFloat }
             *     
             */
            public TargetableFloat getMass() {
                return mass;
            }

            /**
             * Sets the value of the mass property.
             * 
             * @param value
             *     allowed object is
             *     {@link TargetableFloat }
             *     
             */
            public void setMass(TargetableFloat value) {
                this.mass = value;
            }

            /**
             * Gets the value of the density property.
             * 
             * @return
             *     possible object is
             *     {@link TargetableFloat }
             *     
             */
            public TargetableFloat getDensity() {
                return density;
            }

            /**
             * Sets the value of the density property.
             * 
             * @param value
             *     allowed object is
             *     {@link TargetableFloat }
             *     
             */
            public void setDensity(TargetableFloat value) {
                this.density = value;
            }

            /**
             * Gets the value of the physicsMaterial property.
             * 
             * @return
             *     possible object is
             *     {@link PhysicsMaterial }
             *     
             */
            public PhysicsMaterial getPhysicsMaterial() {
                return physicsMaterial;
            }

            /**
             * Sets the value of the physicsMaterial property.
             * 
             * @param value
             *     allowed object is
             *     {@link PhysicsMaterial }
             *     
             */
            public void setPhysicsMaterial(PhysicsMaterial value) {
                this.physicsMaterial = value;
            }

            /**
             * Gets the value of the instancePhysicsMaterial property.
             * 
             * @return
             *     possible object is
             *     {@link InstanceWithExtra }
             *     
             */
            public InstanceWithExtra getInstancePhysicsMaterial() {
                return instancePhysicsMaterial;
            }

            /**
             * Sets the value of the instancePhysicsMaterial property.
             * 
             * @param value
             *     allowed object is
             *     {@link InstanceWithExtra }
             *     
             */
            public void setInstancePhysicsMaterial(InstanceWithExtra value) {
                this.instancePhysicsMaterial = value;
            }

            /**
             * Gets the value of the taperedCapsule property.
             * 
             * @return
             *     possible object is
             *     {@link TaperedCapsule }
             *     
             */
            public TaperedCapsule getTaperedCapsule() {
                return taperedCapsule;
            }

            /**
             * Sets the value of the taperedCapsule property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaperedCapsule }
             *     
             */
            public void setTaperedCapsule(TaperedCapsule value) {
                this.taperedCapsule = value;
            }

            /**
             * Gets the value of the capsule property.
             * 
             * @return
             *     possible object is
             *     {@link Capsule }
             *     
             */
            public Capsule getCapsule() {
                return capsule;
            }

            /**
             * Sets the value of the capsule property.
             * 
             * @param value
             *     allowed object is
             *     {@link Capsule }
             *     
             */
            public void setCapsule(Capsule value) {
                this.capsule = value;
            }

            /**
             * Gets the value of the taperedCylinder property.
             * 
             * @return
             *     possible object is
             *     {@link TaperedCylinder }
             *     
             */
            public TaperedCylinder getTaperedCylinder() {
                return taperedCylinder;
            }

            /**
             * Sets the value of the taperedCylinder property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaperedCylinder }
             *     
             */
            public void setTaperedCylinder(TaperedCylinder value) {
                this.taperedCylinder = value;
            }

            /**
             * Gets the value of the cylinder property.
             * 
             * @return
             *     possible object is
             *     {@link Cylinder }
             *     
             */
            public Cylinder getCylinder() {
                return cylinder;
            }

            /**
             * Sets the value of the cylinder property.
             * 
             * @param value
             *     allowed object is
             *     {@link Cylinder }
             *     
             */
            public void setCylinder(Cylinder value) {
                this.cylinder = value;
            }

            /**
             * Gets the value of the sphere property.
             * 
             * @return
             *     possible object is
             *     {@link Sphere }
             *     
             */
            public Sphere getSphere() {
                return sphere;
            }

            /**
             * Sets the value of the sphere property.
             * 
             * @param value
             *     allowed object is
             *     {@link Sphere }
             *     
             */
            public void setSphere(Sphere value) {
                this.sphere = value;
            }

            /**
             * Gets the value of the box property.
             * 
             * @return
             *     possible object is
             *     {@link Box }
             *     
             */
            public Box getBox() {
                return box;
            }

            /**
             * Sets the value of the box property.
             * 
             * @param value
             *     allowed object is
             *     {@link Box }
             *     
             */
            public void setBox(Box value) {
                this.box = value;
            }

            /**
             * Gets the value of the plane property.
             * 
             * @return
             *     possible object is
             *     {@link Plane }
             *     
             */
            public Plane getPlane() {
                return plane;
            }

            /**
             * Sets the value of the plane property.
             * 
             * @param value
             *     allowed object is
             *     {@link Plane }
             *     
             */
            public void setPlane(Plane value) {
                this.plane = value;
            }

            /**
             * Gets the value of the instanceGeometry property.
             * 
             * @return
             *     possible object is
             *     {@link InstanceGeometry }
             *     
             */
            public InstanceGeometry getInstanceGeometry() {
                return instanceGeometry;
            }

            /**
             * Sets the value of the instanceGeometry property.
             * 
             * @param value
             *     allowed object is
             *     {@link InstanceGeometry }
             *     
             */
            public void setInstanceGeometry(InstanceGeometry value) {
                this.instanceGeometry = value;
            }

            /**
             * Gets the value of the translatesAndRotates property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the translatesAndRotates property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTranslatesAndRotates().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Rotate }
             * {@link TargetableFloat3 }
             * 
             * 
             */
            public List<Object> getTranslatesAndRotates() {
                if (translatesAndRotates == null) {
                    translatesAndRotates = new ArrayList<Object>();
                }
                return this.translatesAndRotates;
            }

            /**
             * 
             * 												The extra element may appear any number of times.
             * 												Gets the value of the extras property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the extras property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExtras().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Extra }
             * 
             * 
             */
            public List<Extra> getExtras() {
                if (extras == null) {
                    extras = new ArrayList<Extra>();
                }
                return this.extras;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.collada.org/2005/11/COLLADASchema>bool">
             *       &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Hollow {

                @XmlValue
                protected boolean value;
                @XmlAttribute
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NCName")
                protected String sid;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public boolean isValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(boolean value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the sid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSid() {
                    return sid;
                }

                /**
                 * Sets the value of the sid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSid(String value) {
                    this.sid = value;
                }

            }

        }

    }

}
